# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('colonia', models.CharField(max_length=200)),
                ('codigopostal', models.IntegerField(default=0)),
                ('ciudad', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('superficie', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('construccion', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('recamaras', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.house'),
        ),
    ]
